### ISSUE TITLE
i'm stuck with an fetal error, where i have to the Endroid package?

### ISSUE THREAD

**Issue by mahivitsit** [acelaya/ZF2-AcQrCode#7]
Hi...

when i run this in my localhost http://localhost/ZendSkeletonApplication/public/qr-code/generate/12345.png/600 it is showing fetal error as: 
Class 'Endroid\QrCode\QrCode' not found in ...\ZendSkeletonApplication\module\Acelaya\QrCode\src\Service\QrCodeService.php on line 68

I have put the Endroid folder in Acelaya Folder.

**Comment by acelaya** [comment]
The only supported installation method is composer.
You need to use it in order to install all dependencies. Otherwise you will
need to manually download and setup autoloading for everything.

--
Alejandro Celaya Alastrué

**Comment by mahivitsit** [comment]
thank you,

i have installed all dependencies using  **"composer.phar require acelaya/zf2-acqrcode:0.*"**

now it's working fine...

**Comment by acelaya** [comment]
That's the way to go ;-)

--
Alejandro Celaya Alastrué
