### ISSUE TITLE
Upgrade to ZF3

### ISSUE THREAD

**Issue by aimfeld** [acelaya/ZF2-AcQrCode#8]
It would be great if you could upgrade this module to ZF3! With ZF3 I get the following error:

Class Acelaya\QrCode\View\Helper\Factory\QrCodeHelperFactory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend\ServiceManager\Factory\FactoryInterface::__invoke)

The factory implementation has changed with ZF3, see [here](https://zendframework.github.io/zend-servicemanager/migration/#factories)

**Comment by acelaya** [comment]
Factories in this project are very simple, so it shouldn't be hard to support both ZF2 and ZF3 using invokable factories.
I'll try to update it.

**Comment by acelaya** [comment]
I'm not going to be able to support both ZF2 and ZF3 at the same time, so starting with v1.0 of this module, only ZF3 will be supported.
Also, minimum PHP version has been bumped to v5.6

**Comment by acelaya** [comment]
Done. I've just pushed v1 of this module.
You should be able to install it soon.

**Comment by aimfeld** [comment]
Thanks, it seems to work!
